version: '3.8'
x-container-common: &container-common
  build:
    context: ./
  depends_on:
    - redis
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - SERVICE_HOST=service
    - SERVICE_PORT=5000
  volumes:
    - ./src:/home/node/src
services:
  service:
    <<: *container-common
    command: sh -c "dockerize -wait tcp://redis:6379 yarn start:service"
    ports:
      - target: 5000
        published: 8080
  standard-queue-worker:
    <<: *container-common
    command: sh -c "dockerize -wait tcp://redis:6379 yarn start:standard-queue-worker"
  rate-limited-queue-worker:
    <<: *container-common
    command: sh -c "dockerize -wait tcp://redis:6379 yarn start:rate-limited-queue-worker"
  redis:
    image: redis:7.0.5-alpine
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: 40001
    volumes:
      - ./redis-data:/data
