version: '3.8'
x-service-defaults: &service-defaults
  build:
    context: ./
  depends_on:
    - redis
  environment:
    - REDIS_URL=redis://redis:6379
  volumes:
    - ./src:/home/node/src
services:
  service:
    <<: *service-defaults
    command: sh -c "dockerize -wait tcp://redis:6379 yarn start:service"
    ports:
      - target: 5000
        published: 8080
  worker:
    <<: *service-defaults
    command: sh -c "dockerize -wait tcp://redis:6379 yarn start:worker"
  redis:
    image: redis:7.0.5-alpine
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: 40001
    volumes:
      - ./redis-data:/data
